### ISSUE TITLE
[BUG] This plugin is not working with Obsidian 0.13.14 

### ISSUE THREAD

**Issue by andrezgz** [JeppeKlitgaard/ObsidianTweaks#4]
Hello,

This is happening with several plugins nowadays, since Obsidian has been updated to CM6.

For example, if I try to apply "Better toggle code" to a text, I get the error `Uncaught TypeError: editor.cm.findWordAt is not a function at BetterFormatting.toggleWrapper` in JS console.

 I've applied a monkey patch in main.js to temporarly keep going. This is the kind of the changes I did in different places (changing how the editor is defined and replacen `findWord` with `wordAt` and anchor/head with from/to)

```diff
@@ -85,13 +88,14 @@ class BetterFormatting {
         if (!activeView) {
             return;
         }
-        const editor = activeView.editor;
+        let activeLeaf = this.app.workspace.activeLeaf;
+        let editor = activeLeaf.view.sourceMode.cmEditor;
         let anchor = editor.getCursor("from");
         let head = editor.getCursor("to");
         let wordStart;
         let wordEnd;
-        wordStart = editor.cm.findWordAt(anchor).anchor;
-        wordEnd = editor.cm.findWordAt(head).head;
+        wordStart = editor.wordAt(anchor).from;
+        wordEnd = editor.wordAt(head).to;
         let textToWrap = editor.getRange(wordStart, wordEnd);
         // Fix for inconsistent toggling
         if (textToWrap.trim() === "") {
```

These changes, applied consistently over the main.js file, get the plugin back on track.

Hope you find the time to fix it properly :)

**Comment by JeppeKlitgaard** [comment]
Hey Andrezgz

**Comment by JeppeKlitgaard** [comment]
Hey @andrezgz,

You're absolutely right! This was written some time before CM6 was introduced for Desktop and I believe the Obsidian API has been improved to better accommodate some of the functionality needed for this plugin.

I don't have too much time on my hands currently and didn't actually realise people still used ObsidianTweaks! If I get the chance I'll review the code and hopefully get around to fixing this! I expect I will get to this soon, but no promises!

Thank you for the kind bug report!

**Comment by JeppeKlitgaard** [comment]
This should now have been fixed.

I'll go through ahead and resubmit this to the Community Plugins list

**Comment by andrezgz** [comment]
Thanks it's working again now.  Hope you get it approved to be available from the Community Plugins list.
